Controllers/CitaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoFinal.Models;
using ProyectoFinal.Models.Entidades;

namespace ProyectoFinal.Controllers
{
    public class CitaController : Controller
    {
        public readonly HospitalContext _context;

        public CitaController(HospitalContext context)
        { 
            _context = context;
        }
        public async Task<IActionResult> ListadoCitas()
        { 
            return View(await _context.Citas.ToListAsync());
        }

        public IActionResult Crear() 
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Cita cita)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cita);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Cita creada exitosamente";
                return RedirectToAction("ListadoCitas");
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Ha ocurrido un error");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.Citas == null)
            { 
                return NotFound();
            }

            var citas = await _context.Citas.FindAsync(id);

            if (citas == null)
            {
                return NotFound();
            }

            return View(citas);
        }
        public async Task<IActionResult> Editar(int IdCita, Cita cita)
        { 
            if(IdCita != cita.IdCita)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cita);
                    await _context.SaveChangesAsync();
                    TempData["AlerMessage"] = "Cita Actualizada" + "Exitosamente!";
                    return RedirectToAction("ListadoCitas");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(ex.Message, "Ocurrio un error" + "Al actualizar");

                }
            }

            return View(cita);
        }

        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.Citas == null) 
            {
                return NotFound();
            }
            var citas = await _context.Citas.FirstOrDefaultAsync(a => a.IdCita == id);
            if (citas == null)
            {
                return NotFound();
            }
            try 
            {
                _context.Citas.Remove(citas);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Cita Eliminada Exitosamente";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Message, "Ocurrio un error, no se pudo eliminar el registro");
            }
            return RedirectToAction(nameof(ListadoCitas));
        }

    }
}

Controllers/ConsultorioController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProyectoFinal.Controllers
{
    public class ConsultorioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HorarioController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoFinal.Models.Entidades;
using ProyectoFinal.Models;
using Microsoft.EntityFrameworkCore;

namespace ProyectoFinal.Controllers
{
    public class HorarioController : Controller
    {
        public readonly HospitalContext _context;

        public HorarioController(HospitalContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListadoHorario()
        {
            return View(await _context.Horarios.ToListAsync());
        }

        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Horario horario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(horario);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Horario creado exitosamente";
                return RedirectToAction("ListadoHorario");
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Ha ocurrido un error");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.Horarios == null)
            {
                return NotFound();
            }

            var horario = await _context.Horarios.FindAsync(id);

            if (horario == null)
            {
                return NotFound();
            }

            return View(horario);
        }
        public async Task<IActionResult> Editar(int IdHorario, Horario horario)
        {
            if (IdHorario != horario.IdHorario)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(horario);
                    await _context.SaveChangesAsync();
                    TempData["AlerMessage"] = "Horario Actualizado" + "Exitosamente!";
                    return RedirectToAction("ListadoHorario");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(ex.Message, "Ocurrio un error" + "Al actualizar");

                }
            }

            return View(horario);
        }

        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.Horarios == null)
            {
                return NotFound();
            }
            var horario = await _context.Horarios.FirstOrDefaultAsync(a => a.IdHorario == id);
            if (horario == null)
            {
                return NotFound();
            }
            try
            {
                _context.Horarios.Remove(horario);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Horario Eliminado Exitosamente";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Message, "Ocurrio un error, no se pudo eliminar el registro");
            }
            return RedirectToAction(nameof(ListadoHorario));
        }
    }
}

Controllers/PacienteController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoFinal.Models.Entidades;
using ProyectoFinal.Models;
using Microsoft.EntityFrameworkCore;

namespace ProyectoFinal.Controllers
{
    public class PacienteController : Controller
    {
        public readonly HospitalContext _context;

        public PacienteController(HospitalContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListadoPaciente()
        {
            return View(await _context.Pacientes.ToListAsync());
        }

        public IActionResult Crear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paciente);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Paciente creado exitosamente";
                return RedirectToAction("ListadoPaciente");
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Ha ocurrido un error");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.Pacientes == null)
            {
                return NotFound();
            }

            var paciente = await _context.Pacientes.FindAsync(id);

            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }
        public async Task<IActionResult> Editar(int IdPaciente, Paciente paciente)
        {
            if (IdPaciente != paciente.IdPaciente)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paciente);
                    await _context.SaveChangesAsync();
                    TempData["AlerMessage"] = "Paciente Actualizado" + "Exitosamente!";
                    return RedirectToAction("ListadoPaciente");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(ex.Message, "Ocurrio un error" + "Al actualizar");

                }
            }

            return View(paciente);
        }

        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null || _context.Pacientes == null)
            {
                return NotFound();
            }
            var paciente = await _context.Pacientes.FirstOrDefaultAsync(a => a.IdPaciente == id);
            if (paciente == null)
            {
                return NotFound();
            }
            try
            {
                _context.Pacientes.Remove(paciente);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Paciente Eliminado Exitosamente";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Message, "Ocurrio un error, no se pudo eliminar el registro");
            }
            return RedirectToAction(nameof(ListadoPaciente));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoFinal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoFinal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cita" asp-action="Privacy">Cita</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ConsultaMedica" asp-action="Index">Consulta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultorio" asp-action="Index">Consultorio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Horario" asp-action="Index">Horario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medico" asp-action="Index">Medico</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paciente" asp-action="Index">Paciente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RecetaMedica" asp-action="Index">Receta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ServiciosMedicos" asp-action="Index">Servicios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProyectoFinal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>